# Feel free to modify as you wish,
# the below are prepopulated with the
# defaults from the project, but you can remove
# them if you wish - their defaults will stay the same.
MEMORY_MAX = 1024
PROC_SIZE_MAX = 256
NUM_PROC = 12
MAX_PROC_TIME = 10000
